### ISSUE TITLE
Tests for {{first}} templates with literal components

### ISSUE THREAD

**Issue by ede-wolf-gls** [OpenCageData/address-formatting#110]
I checked out the [Javascript](https://github.com/fragaria/address-formatter) implementation for address formatting and stumbled upon an issue. The `{{#first}}` lambda splits the text inside the `{{#first}}...{{/first}}` block at the `||` signs and then uses the first component, that's not empty. But this would break, as soon as there is one block, that uses a literal (I think, also other implementations have the same issue).

So lets do an example. Lets see the address format for the Philippines:
```yaml
PH:
    address_template: |
        {{{attention}}}
        {{{house}}}
        {{{house_number}}} {{{road}}}, {{#first}} {{{suburb}}}, || {{{city_district}}}, || {{{neighbourhood}}}, {{/first}} {{#first}} {{{city}}} || {{{town}}} || {{{village}}} || {{{hamlet}}} || {{{suburb}}} || {{{state_district}}} {{/first}}
        {{{postcode}}} {{#first}} {{{municipality}}} {{{region}}} {{{state}}} {{/first}}
        {{{country}}}
```

When we now use the [last test case](https://github.com/OpenCageData/address-formatting/blob/5aaee31252362229f164c218dc7de29d5e02a128/testcases/countries/ph.yaml#L36) from the Philippines test cases and exchange the `suburb` with `city_district`, I would expect the same outcome.

```yaml
description: address 
components:
    house_number: 121 
    road: Epifanio Delos Santos Ave.
    city: Mandaluyong
    postcode: 1550
    city_district: Wack-wack Greenhills
    county: Fifth District
    country: Philippines
    country_code: PH
    attention: Mr. Juan Maliksi
    state: Metro Manila
expected:  |
    Mr. Juan Maliksi
    121 Epifanio Delos Santos Ave., Wack-wack Greenhills, Mandaluyong
    1550 Metro Manila
    Philippines
```

But the result is
```
Mr. Juan Maliksi
121 Epifanio Delos Santos Ave., Mandaluyong
1550 Metro Manila
Philippines
```

Now my question is, did I maybe understand the `first` block wrong (I couldn't find a proper definition in the repository), or should there be a test case for cases like this? Or maybe both.
I can (of course) also open this issue in the javascript repository, but I thought, a test case that would be used in all implementations might be helpful. So I created first here the issue.

There might be similar issues with countries using the `generic2`, `fallback1`, `CA_fr` or `SG` template.
